// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"

	internal "github.com/StackGuardian/sg-sdk-go/internal"
)

type ListAllConnectorsRequest struct {
	// Filter the results based on the resource name.
	ResourceNames *string `json:"-" url:"ResourceNames,omitempty"`
	// Filter the results based on the kind of Connector using comma separated values. For example: `AWS_RBAC,AWS_OIDC,AWS_STATIC,AZURE_STATIC,AZURE_OIDC,GCP_STATIC,GCP_OIDC`.
	Kind *string `json:"-" url:"kind,omitempty"`
	// Last evaluated key for pagination. Use this to get the next set of results.
	Lastevaluatedkey *string `json:"-" url:"lastevaluatedkey,omitempty"`
	// Limit the number of results returned. Default is 50. Maximum is 500.
	Limit *int `json:"-" url:"limit,omitempty"`
}

type GeneratedConnectorDeleteResponse struct {
	Msg string `json:"msg" url:"msg"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GeneratedConnectorDeleteResponse) GetMsg() string {
	if g == nil {
		return ""
	}
	return g.Msg
}

func (g *GeneratedConnectorDeleteResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GeneratedConnectorDeleteResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GeneratedConnectorDeleteResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GeneratedConnectorDeleteResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GeneratedConnectorDeleteResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GeneratedConnectorListAllResponseMsg struct {
	Lastevaluatedkey string                            `json:"lastevaluatedkey" url:"lastevaluatedkey"`
	Msg              []*GeneratedConnectorReadResponse `json:"msg,omitempty" url:"msg,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GeneratedConnectorListAllResponseMsg) GetLastevaluatedkey() string {
	if g == nil {
		return ""
	}
	return g.Lastevaluatedkey
}

func (g *GeneratedConnectorListAllResponseMsg) GetMsg() []*GeneratedConnectorReadResponse {
	if g == nil {
		return nil
	}
	return g.Msg
}

func (g *GeneratedConnectorListAllResponseMsg) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GeneratedConnectorListAllResponseMsg) UnmarshalJSON(data []byte) error {
	type unmarshaler GeneratedConnectorListAllResponseMsg
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GeneratedConnectorListAllResponseMsg(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GeneratedConnectorListAllResponseMsg) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GeneratedConnectorReadResponse struct {
	Msg *GeneratedConnectorReadResponseMsg `json:"msg,omitempty" url:"msg,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GeneratedConnectorReadResponse) GetMsg() *GeneratedConnectorReadResponseMsg {
	if g == nil {
		return nil
	}
	return g.Msg
}

func (g *GeneratedConnectorReadResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GeneratedConnectorReadResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GeneratedConnectorReadResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GeneratedConnectorReadResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GeneratedConnectorReadResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type IntegrationCreateResponse struct {
	Msg  *string                            `json:"msg,omitempty" url:"msg,omitempty"`
	Data *GeneratedConnectorReadResponseMsg `json:"data,omitempty" url:"data,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IntegrationCreateResponse) GetMsg() *string {
	if i == nil {
		return nil
	}
	return i.Msg
}

func (i *IntegrationCreateResponse) GetData() *GeneratedConnectorReadResponseMsg {
	if i == nil {
		return nil
	}
	return i.Data
}

func (i *IntegrationCreateResponse) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *IntegrationCreateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler IntegrationCreateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IntegrationCreateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IntegrationCreateResponse) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}
