// This file was auto-generated by Fern from our API Definition.

package api

type RunnerGroup struct {
	ResourceName         *string                `json:"ResourceName,omitempty" url:"-"`
	Tags                 []string               `json:"Tags,omitempty" url:"-"`
	Description          *string                `json:"Description,omitempty" url:"-"`
	MaxNumberOfRunners   *int                   `json:"MaxNumberOfRunners,omitempty" url:"-"`
	StorageBackendConfig map[string]interface{} `json:"StorageBackendConfig,omitempty" url:"-"`
	IsActive             *IsArchiveEnum         `json:"IsActive,omitempty" url:"-"`
	// Time in milliseconds as a string
	CreatedAt string `json:"CreatedAt" url:"-"`
	// Time in milliseconds as a string
	ModifiedAt            string                   `json:"ModifiedAt" url:"-"`
	ParentId              string                   `json:"ParentId" url:"-"`
	ResourceType          string                   `json:"ResourceType" url:"-"`
	RunnerToken           *string                  `json:"RunnerToken,omitempty" url:"-"`
	ContainerInstances    []map[string]interface{} `json:"ContainerInstances,omitempty" url:"-"`
	ActiveWorkflows       map[string]interface{}   `json:"ActiveWorkflows,omitempty" url:"-"`
	QueuedWorkflowsCount  int                      `json:"QueuedWorkflowsCount" url:"-"`
	PendingWorkflowsCount int                      `json:"PendingWorkflowsCount" url:"-"`
	RunningWorkflowsCount int                      `json:"RunningWorkflowsCount" url:"-"`
}

type RunnerDeregister struct {
	RunnerId              *string  `json:"RunnerId,omitempty" url:"-"`
	ContainerInstanceArns []string `json:"ContainerInstanceArns,omitempty" url:"-"`
	ForceDeregister       *bool    `json:"ForceDeregister,omitempty" url:"-"`
}

type ReadRunnerGroupRequest struct {
	GetActiveWorkflows        *bool `json:"-" url:"getActiveWorkflows,omitempty"`
	GetActiveWorkflowsDetails *bool `json:"-" url:"getActiveWorkflowsDetails,omitempty"`
}

type RunnerStatus struct {
	RunnerId              *string    `json:"RunnerId,omitempty" url:"-"`
	ContainerInstanceArns []string   `json:"ContainerInstanceArns,omitempty" url:"-"`
	Status                StatusEnum `json:"Status" url:"-"`
}
