// This file was auto-generated by Fern from our API Definition.

package api

type StackAction struct {
	ResourceName *string        `json:"ResourceName,omitempty" url:"-"`
	ActionType   ActionTypeEnum `json:"ActionType" url:"-"`
}
