// This file was auto-generated by Fern from our API Definition.

// A Workflow run refers to a single execution instance of a defined workflow, where the actions specified in the workflow configuration are carried out.
//
// For more details, visit our [Documentation](https://docs.stackguardian.io/docs/deploy/workflows/workflow_components/run/).
package workflowruns
