// This file was auto-generated by Fern from our API Definition.

// A Stack Workflow Run refers to a single execution instance of a defined Stack Workflow, where the actions specified in the Stack Workflow configuration are carried out.
//
// For more details, please visit our Workflow Runs [Documentation](https://docs.stackguardian.io/docs/deploy/workflows/workflow_components/run/).
package stackworkflowruns
