// This file was auto-generated by Fern from our API Definition.

// A Stack run refers to a single execution instance of a defined stack, where the actions specified in the stack run configuration are carried out.
//
// For more details, visit our [Documentation](https://docs.stackguardian.io/docs/deploy/stack/overview/).
package stackruns
