// This file was auto-generated by Fern from our API Definition.

// Templates are automated blueprints for provisioning cloud infrastructure. They support rapid deployment with features like version control, JSON-based configurations, and customizable settings for infrastructure components.
//
// For more details, visit our [Documentation](https://docs.stackguardian.io/docs/develop/library/overview/).
package templates
