// This file was auto-generated by Fern from our API Definition.

// A Stack Workflow refers to a Workflow that is part of a Stack. A Stack Workflow is the same as an individual Workflow but is contained within a Stack.
//
// For more details, please visit our workflow [Documentaion](https://docs.stackguardian.io/docs/deploy/workflows/overview/).
package stackworkflows
