// This file was auto-generated by Fern from our API Definition.

// Secrets provide a secure solution for storing sensitive data like credentials and API keys.
//
// For more details, visit our [Documentation](https://docs.stackguardian.io/docs/connectors/vaults)
package secrets
